### ISSUE TITLE
执行sdkmanager --list 出现异常

### ISSUE THREAD

**Issue by storytellerF** [lzhiyong/termux-ndk#135]
>Warning: Could not create settings
java.lang.IllegalArgumentException
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)

**Comment by storytellerF** [comment]
是这个原因。
log 是全的（后面会打印一堆usage 的文档）。

不过这样每次都需要指定太麻烦了，只要把路径改成android 要求的路径就可以不用指定`--sdk_root`了。
```shell
android-sdk-package/android-sdk/cmdline-tools/latest/bin/sdkmanager --list
```

**Comment by storytellerF** [comment]
同样的命令，使用这种方式，在执行的时候还会提示
>Installed packages:=====================] 100% Computing updates...             
  Path                 | Version | Description                    | Location             
  -------              | ------- | -------                        | -------              
  build-tools;33.0.0   | 33.0.0  | Android SDK Build-Tools 33     | build-tools/33.0.0/  
  build-tools;33.0.1   | 33.0.1  | Android SDK Build-Tools 33.0.1 | build-tools/33.0.1/  
  platform-tools       | 33.0.3  | Android SDK Platform-Tools     | platform-tools/      
  platforms;android-30 | 3       | Android SDK Platform 30        | platforms/android-30/
  platforms;android-31 | 1       | Android SDK Platform 31        | platforms/android-31/
  platforms;android-32 | 1       | Android SDK Platform 32        | platforms/android-32/
  platforms;android-33 | 2       | Android SDK Platform 33        | platforms/android-33/
  tools                | 2.0.0   | Android SDK Tools 2            | cmdline-tools/latest

前者的方式是没有这个提示的
