### ISSUE TITLE
Can Be used in Chrooted Linux??

### ISSUE THREAD

**Issue by 0x300T** [Lzhiyong/termux-ndk#15]
I use chrooted kali-linux from kali-nethunter.Can your ndk toolchain from release be used in chrooted linux??Actually i tried to built app with your tools,but ran into some api related problem.
and Can you make the app built section in readme with some extra details?? Kinda confused

```
# setting the buildToolsVersion
# update buildToolsVersion you need download the sdk-tools, then copy it to android-sdk/build-tools platform-tools
# sdk-tools from https://github.com/Lzhiyong/sdk-tools
buildToolsVersion "30.0.1"
```

can you explain this part?? 

and was building termux,don't know possible or not

faced this

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /root/android-ndk-r22/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/root/termux-app/app/src/main/cpp/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-24 NDK_OUT=/root/termux-app/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/root/termux-app/app/build/intermediates/ndkBuild/debug/lib APP_CFLAGS+=-std=c11 APP_CFLAGS+=-Wall APP_CFLAGS+=-Wextra APP_CFLAGS+=-Werror APP_CFLAGS+=-Os APP_CFLAGS+=-fno-stack-protector APP_CFLAGS+=-Wl,--gc-sections APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  ERROR: Unknown host CPU architecture: aarch64

```

unkown aarch

**Comment by Lzhiyong** [comment]
* To fix this problem, please refer to [ndk-build](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/ndk-build.patch)
* I have updated android-ndk-r22 and android-sdk, please download them again
* How to build android app, please refer to [build-apk](https://github.com/Lzhiyong/termux-ndk/tree/master/build-apk)

**Comment by 0x300T** [comment]
Thanks for solving issue
will try again

**Comment by 0x300T** [comment]
> * To fix this problem, please refer to [ndk-build](https://github.com/Lzhiyong/termux-ndk/blob/master/patches/ndk-build.patch)
> * I have updated android-ndk-r22 and android-sdk, please download them again
> * How to build android app, please refer to [build-app](https://github.com/Lzhiyong/termux-ndk/tree/master/build-app)

Hey brother, All is working.But when building termux, :app:generateJsonModelDebug this is executing like 30 mins and my mobile did not take the load(4GB RAM,64GB SPACE) and got rebooted

i started again,seems that it started from beginning

can you tell me what is happening?? the pic is after reboot
![Screenshot_2021-02-08-16-48-15-571_com offsec nhterm](https://user-images.githubusercontent.com/78304032/107213851-3f21fb00-6a33-11eb-908a-bacdccc79ed9.jpg)

**Comment by Lzhiyong** [comment]
It is not recommended to use chroot linux, directly use native termux to build

**Comment by 0x300T** [comment]
> It is not recommended to use chroot linux, the speed will be very slow, please use native termux to build directly.

is it necessary to use termuxARCH??or i can just use termux like default, just setting it?cause i faced permission denied when setting up java

**Comment by Lzhiyong** [comment]
> > It is not recommended to use chroot linux, the speed will be very slow, please use native termux to build directly.
> 
> is it necessary to use termuxARCH??or i can just use termux like default, just setting it?cause i faced permission denied when setting up java

Yes, you can try [TermuxArch](https://github.com/SDRausty/TermuxArch)

**Comment by 0x300T** [comment]
> > > It is not recommended to use chroot linux, the speed will be very slow, please use native termux to build directly.
> > 
> > 
> > is it necessary to use termuxARCH??or i can just use termux like default, just setting it?cause i faced permission denied when setting up java
> 
> Yes, you can try [TermuxArch](https://github.com/SDRausty/TermuxArch)

installing now, removing the chroot. and which build essential toolchain you recommend??

One request: You Can Open A telegram group of your own. and add it in the readme.

**Comment by 0x300T** [comment]
![Screenshot_2021-02-08-20-37-15-051_com termux](https://user-images.githubusercontent.com/78304032/107234071-7ac9be80-6a4d-11eb-861a-e0431cbc3a38.jpg)
Natively building termux.Faced this.Any Solution??

**Comment by 0x300T** [comment]
![Screenshot_2021-02-08-20-46-31-757_com termux](https://user-images.githubusercontent.com/78304032/107235285-bf098e80-6a4e-11eb-8192-9cb0dd31e315.jpg)
faced this
ran twice. I have stable network.Any Solution??
also saw this warning

```
WARN: Unable to load JNA library (OS: Linux 4.14.181-0x300t)
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/home/.cache/JNA/temp/jna14970918408052608912.tmp: dlopen failed: library "libc.so.6" not found
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.intellij.jna.JnaLoader.load(JnaLoader.java:16)
        at com.intellij.jna.JnaLoader.isLoaded(JnaLoader.java:29)
        at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:54)
        at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:46)
        at com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:62)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:44)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
        at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:61)
        at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:54)
        at com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:84)
        at com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:131)
        at com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:47)
        at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:183)
        at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
        at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
        at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
        at com.intellij.core.JavaCoreProjectEnvironment.addJarToClassPath(JavaCoreProjectEnvironment.java:79)
        at com.android.tools.lint.UastEnvironment$ProjectEnvironment.registerPaths(UastEnvironment.kt:201)
        at com.android.tools.lint.LintCliClient.initializeProjects(LintCliClient.kt:1049)
        at com.android.tools.lint.client.api.LintClient.performInitializeProjects$lint_api(LintClient.kt:892)
        at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.kt:401)
        at com.android.tools.lint.LintCliClient.run(LintCliClient.kt:256)
        at com.android.tools.lint.LintCliClient.run(LintCliClient.kt:237)
        at com.android.tools.lint.gradle.LintGradleClient.run(LintGradleClient.kt:255)
        at com.android.tools.lint.gradle.LintGradleExecution.runLint(LintGradleExecution.kt:259)
        at com.android.tools.lint.gradle.LintGradleExecution.lintAllVariants(LintGradleExecution.kt:318)
        at com.android.tools.lint.gradle.LintGradleExecution.analyze(LintGradleExecution.kt:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.android.tools.lint.gradle.api.ReflectiveLintRunner.runLint(ReflectiveLintRunner.kt:38)
        at com.android.build.gradle.tasks.LintBaseTask.runLint(LintBaseTask.java:117)
        at com.android.build.gradle.tasks.LintGlobalTask.lint(LintGlobalTask.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:479)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:462)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$400(ExecuteActionsTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:251)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$executeOperation$1(ExecuteStep.java:66)
        at java.base/java.util.Optional.orElseGet(Unknown Source)
        at org.gradle.internal.execution.steps.ExecuteStep.executeOperation(ExecuteStep.java:66)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:34)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:34)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:72)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:42)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:53)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:39)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:44)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:77)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:58)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:54)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:32)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:57)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:63)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:30)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:176)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:76)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:39)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:25)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:102)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:95)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:83)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:96)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:52)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:83)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:54)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:88)
        at java.base/java.util.Optional.orElseGet(Unknown Source)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:88)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:46)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:34)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:43)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$3.withWorkspace(ExecuteActionsTaskExecuter.java:286)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:43)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:33)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:40)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:30)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:54)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:40)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine.rebuild(DefaultExecutionEngine.java:46)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$0(ExecuteActionsTaskExecuter.java:182)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:182)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Unknown Source)
Ran lint on variant debug: 10 issues found
Ran lint on variant release: 10 issues found
Wrote HTML report to file:///data/data/com.termux/files/home/project/termux-app/app/build/reports/lint-results.html
Wrote XML report to file:///data/data/com.termux/files/home/project/termux-app/app/build/reports/lint-results.xml
```

**Comment by Lzhiyong** [comment]
Why is there no error in my termux, try to disable lint 
```bash
android {
    ......
    lintOptions {
        abortOnError false
    }
    ......
}
```

**Comment by 0x300T** [comment]
> Why is there no error in my termux, try to disable lint
> 
> ```shell
> android {
>     ......
>     lintOptions {
>         abortOnError false
>     }
>     ......
> }
> ```

same.I added buildversion in every build gradle
and the two mentioned line in termux section you mentioned.Is it okay??

do i need to add cmake option in every gradle or just app/build.gradle??

**Comment by Lzhiyong** [comment]
just add buildversion is ok, cmake option is not necessary

**Comment by 0x300T** [comment]
> just add buildversion is ok, cmake option is not necessary

then,What may cause it??i followed your guide one by one. even moved to native from chroot

i also see libc.so.6 is missing
in java.

```
WARN: Unable to load JNA library (OS: Linux 4.14.181-0x300t)
java.lang.UnsatisfiedLinkError: /data/data/com.termux/files/home/.cache/JNA/temp/jna14970918408052608912.tmp: dlopen failed: library "libc.so.6" not found
```

**Comment by Lzhiyong** [comment]
The warning comes from libjansi.so
in ~/.gradle./native/jansi/1.18/linux64/libjansi.so

**Comment by 0x300T** [comment]
> The warning comes from libjansi.so
> in ~/.gradle./native/jansi/1.18/linux64/libjansi.so
> Did you build termux-app successfully？

no
that error still there
i am pushing my changes to own fork termux app
if you can look at chnages

**Comment by 0x300T** [comment]
https://github.com/0x300T/termux-app/commit/820fe0821723223e0ffe6866bd758fdca5a21319

can you check it??

and one thing
`buildToolsVersion project.properties.ndkVersion`
is this line from your readme right??asking cause it was downloading 29.0.2.this should not be happened cause i set 30.0.3

i think this would be like this
`buildToolsVersion project.properties.`buildToolsVersion`

if you can look all these.i may be wrong

**Comment by Lzhiyong** [comment]
> [0x300T/termux-app@820fe08](https://github.com/0x300T/termux-app/commit/820fe0821723223e0ffe6866bd758fdca5a21319)
> 
> can you check it??
> 
> and one thing
> `buildToolsVersion project.properties.ndkVersion`
> is this line from your readme right??asking cause it was downloading 29.0.2.this should not be happened cause i set 30.0.3
> 
> i think this would be like this
> `buildToolsVersion project.properties.buildToolsVersion`
> 
> if you can look all these.i may be wrong

Sorry for wrong, buildToolsVersion should be 30.0.3

**Comment by 0x300T** [comment]
> > [0x300T/termux-app@820fe08](https://github.com/0x300T/termux-app/commit/820fe0821723223e0ffe6866bd758fdca5a21319)
> > can you check it??
> > and one thing
> > `buildToolsVersion project.properties.ndkVersion`
> > is this line from your readme right??asking cause it was downloading 29.0.2.this should not be happened cause i set 30.0.3
> > i think this would be like this
> > `buildToolsVersion project.properties.buildToolsVersion`
> > if you can look all these.i may be wrong
> 
> Sorry for wrong, buildToolsVersion should be 30.0.3

just replacing ndkversion with buildtoolsversion fixes it

but did you check the commit??is anything chnages required more??

**Comment by Lzhiyong** [comment]
yes, restart build

**Comment by 0x300T** [comment]
> yes, restart build

```
> Task :app:bundleDebugClasses UP-TO-DATE
> Task :app:preDebugUnitTestBuild UP-TO-DATE
> Task :app:javaPreCompileDebugUnitTest UP-TO-DATE
> Task :app:compileDebugUnitTestJavaWithJavac UP-TO-DATE
> Task :app:packageDebugUnitTestForUnitTest UP-TO-DATE
> Task :app:generateDebugUnitTestConfig UP-TO-DATE
> Task :app:processDebugUnitTestJavaRes NO-SOURCE

> Task :app:testDebugUnitTest

com.termux.filepicker.TermuxFileReceiverActivityTest > testIsSharedTextAnUrl FAILED
    java.lang.RuntimeException at ShadowPackageParser.java:69
        Caused by: java.lang.UnsupportedOperationException at ShadowArscApkAssets9.java:208

2 tests completed, 1 failed

> Task :app:testDebugUnitTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> There were failing tests. See the report at: file:///data/data/com.termux/files/home/project/termux-app/app/build/reports/tests/testDebugUnitTest/index.html
```

same error😪

**Comment by Lzhiyong** [comment]
build termux-ndk/example, will there be the same error.

**Comment by 0x300T** [comment]
> build termux-ndk/example, will there be the same error.

![Screenshot_2021-02-09-00-02-19-519_com termux](https://user-images.githubusercontent.com/78304032/107262029-41ec1280-6a6a-11eb-8505-cc1f92ef7b51.jpg)
successful. What may issue with termux
